"""adiciona campos de pagamento via pix

Revision ID: 50f97271f0a2
Revises: 
Create Date: 2026-08-25 10:33:26.279007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f97271f0a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('provider_payment_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('external_reference', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pix_copia_cola', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ticket_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('data_criacao_pix', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_expiracao', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_pagamentos_external_reference', ['external_reference'])
        batch_op.create_unique_constraint('uq_pagamentos_provider_payment_id', ['provider_payment_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pagamentos_provider_payment_id', type_='unique')
        batch_op.drop_constraint('uq_pagamentos_external_reference', type_='unique')
        batch_op.drop_column('data_expiracao')
        batch_op.drop_column('data_criacao_pix')
        batch_op.drop_column('ticket_url')
        batch_op.drop_column('pix_copia_cola')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('external_reference')
        batch_op.drop_column('provider_payment_id')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
