"""adiciona campos de pagamento via pix

Revision ID: 50f97271f0a2
Revises: 
Create Date: 2026-08-25 10:33:26.279007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f97271f0a2'
down_revision = 'a1f0c3e75b92'
branch_labels = None
depends_on = None


COLUNAS_PIX = (
    ('provider', sa.String(length=20)),
    ('provider_payment_id', sa.String(length=64)),
    ('external_reference', sa.String(length=120)),
    ('idempotency_key', sa.String(length=64)),
    ('pix_copia_cola', sa.Text()),
    ('ticket_url', sa.String(length=255)),
    ('data_criacao_pix', sa.DateTime()),
    ('data_expiracao', sa.DateTime()),
)


RESTRICOES_PIX = (
    ('uq_pagamentos_external_reference', ['external_reference']),
    ('uq_pagamentos_provider_payment_id', ['provider_payment_id']),
)


def upgrade():
    # Mesmo cuidado das revisões seguintes: confere o banco real antes de agir. Um banco
    # criado pelo antigo `db.create_all()` já tem estas colunas, e reaplicar cegamente
    # era o que fazia `flask db upgrade` falhar com "column already exists".
    #
    # Colunas e restrições são conferidas SEPARADAMENTE: sair cedo por já haver as
    # colunas deixava as restrições de unicidade para trás, e criá-las sem conferir
    # falhava num banco que já as tivesse.
    inspector = sa.inspect(op.get_bind())
    colunas = {c['name'] for c in inspector.get_columns('pagamentos')}
    faltantes = [(nome, tipo) for nome, tipo in COLUNAS_PIX if nome not in colunas]

    nomes_existentes = {
        r['name'] for r in inspector.get_unique_constraints('pagamentos') if r.get('name')
    } | {i['name'] for i in inspector.get_indexes('pagamentos')}
    restricoes = [(n, c) for n, c in RESTRICOES_PIX if n not in nomes_existentes]

    if not faltantes and not restricoes:
        return

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        for nome, tipo in faltantes:
            batch_op.add_column(sa.Column(nome, tipo, nullable=True))
        for nome, colunas_da_restricao in restricoes:
            batch_op.create_unique_constraint(nome, colunas_da_restricao)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pagamentos_provider_payment_id', type_='unique')
        batch_op.drop_constraint('uq_pagamentos_external_reference', type_='unique')
        batch_op.drop_column('data_expiracao')
        batch_op.drop_column('data_criacao_pix')
        batch_op.drop_column('ticket_url')
        batch_op.drop_column('pix_copia_cola')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('external_reference')
        batch_op.drop_column('provider_payment_id')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
