"""adiciona foto e graduacao do aluno, campos financeiros e comprovante manual

Revision ID: 896e70afc9c5
Revises: 50f97271f0a2
Create Date: 2026-09-04 00:37:53.379677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896e70afc9c5'
down_revision = '50f97271f0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_arquivo', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('graduacao', sa.String(length=80), nullable=True))

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competencia', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('provider_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('provider_status_detail', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('comprovante_manual_arquivo', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('comprovante_manual_enviado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('comprovante_manual_analisado_por', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('comprovante_manual_analisado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('comprovante_manual_observacao', sa.Text(), nullable=True))
        batch_op.alter_column('valor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.alter_column('preco_plano',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.alter_column('preco_plano',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('comprovante_manual_observacao')
        batch_op.drop_column('comprovante_manual_analisado_em')
        batch_op.drop_column('comprovante_manual_analisado_por')
        batch_op.drop_column('comprovante_manual_enviado_em')
        batch_op.drop_column('comprovante_manual_arquivo')
        batch_op.drop_column('provider_status_detail')
        batch_op.drop_column('provider_status')
        batch_op.drop_column('competencia')

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_column('graduacao')
        batch_op.drop_column('foto_arquivo')

    # ### end Alembic commands ###
