"""adiciona foto e graduacao do aluno, campos financeiros e comprovante manual

Revision ID: 896e70afc9c5
Revises: 50f97271f0a2
Create Date: 2026-09-04 00:37:53.379677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896e70afc9c5'
down_revision = '50f97271f0a2'
branch_labels = None
depends_on = None


COLUNAS_ALUNO = (
    ('foto_arquivo', sa.String(length=64)),
    ('graduacao', sa.String(length=80)),
)

COLUNAS_PAGAMENTO = (
    ('competencia', sa.String(length=7)),
    ('provider_status', sa.String(length=30)),
    ('provider_status_detail', sa.String(length=60)),
    ('comprovante_manual_arquivo', sa.String(length=64)),
    ('comprovante_manual_enviado_em', sa.DateTime()),
    ('comprovante_manual_analisado_por', sa.String(length=100)),
    ('comprovante_manual_analisado_em', sa.DateTime()),
    ('comprovante_manual_observacao', sa.Text()),
)


def _faltantes(inspector, tabela, definicoes):
    existentes = {c['name'] for c in inspector.get_columns(tabela)}
    return [(nome, tipo) for nome, tipo in definicoes if nome not in existentes]


def _e_decimal(inspector, tabela, coluna):
    tipo = next(c['type'] for c in inspector.get_columns(tabela) if c['name'] == coluna)
    return isinstance(tipo, sa.Numeric) and not isinstance(tipo, sa.Float)


def upgrade():
    # Confere o banco real antes de agir: um banco criado pelo antigo `db.create_all()`
    # já nasce com estas colunas e com `valor`/`preco_plano` em Numeric.
    inspector = sa.inspect(op.get_bind())

    faltantes_aluno = _faltantes(inspector, 'alunos', COLUNAS_ALUNO)
    if faltantes_aluno:
        with op.batch_alter_table('alunos', schema=None) as batch_op:
            for nome, tipo in faltantes_aluno:
                batch_op.add_column(sa.Column(nome, tipo, nullable=True))

    faltantes_pagamento = _faltantes(inspector, 'pagamentos', COLUNAS_PAGAMENTO)
    converter_valor = not _e_decimal(inspector, 'pagamentos', 'valor')
    if faltantes_pagamento or converter_valor:
        with op.batch_alter_table('pagamentos', schema=None) as batch_op:
            for nome, tipo in faltantes_pagamento:
                batch_op.add_column(sa.Column(nome, tipo, nullable=True))
            if converter_valor:
                batch_op.alter_column(
                    'valor', type_=sa.Numeric(precision=10, scale=2), existing_nullable=False,
                )

    if not _e_decimal(inspector, 'planos', 'preco_plano'):
        with op.batch_alter_table('planos', schema=None) as batch_op:
            batch_op.alter_column(
                'preco_plano', type_=sa.Numeric(precision=10, scale=2), existing_nullable=False,
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.alter_column('preco_plano',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('comprovante_manual_observacao')
        batch_op.drop_column('comprovante_manual_analisado_em')
        batch_op.drop_column('comprovante_manual_analisado_por')
        batch_op.drop_column('comprovante_manual_enviado_em')
        batch_op.drop_column('comprovante_manual_arquivo')
        batch_op.drop_column('provider_status_detail')
        batch_op.drop_column('provider_status')
        batch_op.drop_column('competencia')

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_column('graduacao')
        batch_op.drop_column('foto_arquivo')

    # ### end Alembic commands ###
