"""add email verificacao

Revision ID: b565d2f8bd5e
Revises: d7a9c1e3f5b8
Create Date: 2026-09-29 15:45:56.819025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b565d2f8bd5e'
down_revision = 'd7a9c1e3f5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verificado', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('token_verificacao_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('token_verificacao_expira', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_alunos_token_verificacao_hash'), ['token_verificacao_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_token_verificacao_hash'))
        batch_op.drop_column('token_verificacao_expira')
        batch_op.drop_column('token_verificacao_hash')
        batch_op.drop_column('email_verificado')

    # ### end Alembic commands ###
